# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeEvent",
            fields=[
                ("sequence", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("aggregate_id", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_events",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "sequence"],
                        name="realtime_re_custome_21010c_idx",
                    )
                ],
            },
        ),
    ]
