# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=120)),
                ("bucket_start", models.DateTimeField()),
                ("bucket_seconds", models.PositiveIntegerField(default=3600)),
                ("minimum", models.FloatField()),
                ("maximum", models.FloatField()),
                ("average", models.FloatField()),
                ("sample_count", models.PositiveIntegerField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_aggregates",
                        to="inventory.machine",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "machine",
                            "metric_name",
                            "bucket_start",
                            "bucket_seconds",
                        ),
                        name="uniq_metric_aggregate_bucket",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NormalizedMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("source_type", models.CharField(max_length=16)),
                ("metric_name", models.CharField(max_length=120)),
                ("metric_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="accounts.customer",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="inventory.environment",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="inventory.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["customer", "timestamp"],
                        name="metrics_nor_custome_48f494_idx",
                    ),
                    models.Index(
                        fields=["machine", "metric_name", "timestamp"],
                        name="metrics_nor_machine_5640e4_idx",
                    ),
                    models.Index(
                        fields=["source_type", "metric_name", "timestamp"],
                        name="metrics_nor_source__0e29fe_idx",
                    ),
                ],
            },
        ),
    ]
