# Generated by Django 6.0.6 on 2026-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizedmetric",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name="normalizedmetric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("customer", "idempotency_key"),
                name="uniq_metric_customer_idempotency",
            ),
        ),
    ]
