# Generated by Django 6.0.6 on 2026-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('monitoring', '0002_alert_uniq_open_alert_customer_dedup'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.UniqueConstraint(fields=('customer', 'dedup_key'), name='uniq_notification_event_customer_dedup'),
        ),
    ]
