# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=80)),
                (
                    "algorithm",
                    models.CharField(default="IsolationForest", max_length=80),
                ),
                ("features", models.JSONField(default=list)),
                ("preprocessing", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=dict)),
                ("dataset", models.JSONField(default=dict)),
                ("evaluation_metrics", models.JSONField(default=dict)),
                ("decision_threshold", models.FloatField(blank=True, null=True)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "En entraînement"),
                            ("READY", "Prêt"),
                            ("FAILED", "Échec"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="TRAINING",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_models",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "version"), name="uniq_ml_customer_version"
                    )
                ],
            },
        ),
    ]
