# Generated by Django 6.0.6 on 2026-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("ml_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mlmodelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("customer",),
                name="uniq_active_ml_model_customer",
            ),
        ),
    ]
