# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échec"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_hosts", models.PositiveIntegerField(default=0)),
                ("discovered_vms", models.PositiveIntegerField(default=0)),
                ("metric_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_runs",
                        to="inventory.integrationendpoint",
                    ),
                ),
            ],
        ),
    ]
