# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échec"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=160)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échec"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task_name", "status", "started_at"],
                        name="async_tasks_task_na_a691e4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_name", "idempotency_key"),
                        name="uniq_task_idempotency_key",
                    )
                ],
            },
        ),
    ]
