# Generated by Django 6.0.6 on 2026-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("async_tasks", "0002_taskrun_customer_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskrun",
            name="uniq_task_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="taskrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False)),
                fields=("customer", "task_name", "idempotency_key"),
                name="uniq_customer_task_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", True)),
                fields=("task_name", "idempotency_key"),
                name="uniq_global_task_idempotency_key",
            ),
        ),
    ]
