# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("VMWARE", "VMware"),
                            ("HYPERV", "Hyper-V"),
                            ("MIXED", "Mixte"),
                        ],
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_codes",
                        to="accounts.customer",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_codes",
                        to="inventory.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VMWARE", "VMware/vCenter"),
                            ("HYPERV", "Microsoft Hyper-V"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("endpoint", models.CharField(max_length=500)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "secret_ref",
                    models.CharField(
                        help_text="Variable d'environnement ou référence de coffre",
                        max_length=255,
                    ),
                ),
                ("verify_tls", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="accounts.customer",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="inventory.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("VMWARE", "VMware"),
                            ("HYPERV", "Hyper-V"),
                            ("MIXED", "Mixte"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("hostname", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("os_information", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "En ligne"),
                            ("OFFLINE", "Hors ligne"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("agent_version", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="accounts.customer",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="inventory.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.CharField(blank=True, max_length=40)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="accounts.customer",
                    ),
                ),
                (
                    "machine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent",
                        to="inventory.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("parent_external_id", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("HOST", "Hôte"),
                            ("VM", "Machine virtuelle"),
                            ("DATASTORE", "Datastore"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="inventory.integrationendpoint",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_assets",
                        to="accounts.customer",
                    ),
                ),
                (
                    "machine",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="virtual_asset",
                        to="inventory.machine",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.UniqueConstraint(
                fields=("customer", "name"), name="uniq_environment_customer_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationendpoint",
            constraint=models.UniqueConstraint(
                fields=("customer", "kind", "name"),
                name="uniq_connector_customer_kind_name",
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["customer", "status"], name="inventory_m_custome_f24c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["environment", "hostname"],
                name="inventory_m_environ_5e4d1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.UniqueConstraint(
                fields=("customer", "source_type", "external_id"),
                name="uniq_machine_source_external",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualasset",
            index=models.Index(
                fields=["customer", "kind"], name="inventory_v_custome_6cf898_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualasset",
            constraint=models.UniqueConstraint(
                fields=("connector", "external_id"),
                name="uniq_asset_connector_external",
            ),
        ),
    ]
