# Generated by Django 6.0.6 on 2026-08-24 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("metrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("HIGH", "Élevée"),
                            ("CRITICAL", "Critique"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("anomaly_score", models.FloatField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouvelle"),
                            ("ACKNOWLEDGED", "Acquittée"),
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolue"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("dedup_key", models.CharField(db_index=True, max_length=180)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="accounts.customer",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("score", models.FloatField()),
                ("threshold", models.FloatField()),
                ("model_version", models.CharField(max_length=80)),
                ("explanation", models.JSONField(default=dict)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="accounts.customer",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="inventory.machine",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalies",
                        to="metrics.normalizedmetric",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(blank=True, max_length=120)),
                ("target_id", models.CharField(blank=True, max_length=120)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("metric", models.CharField(max_length=120)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", ">"),
                            ("<", "<"),
                            (">=", ">="),
                            ("<=", "<="),
                            ("==", "=="),
                            ("!=", "!="),
                        ],
                        max_length=2,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("HIGH", "Élevée"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="WARNING",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("cooldown_seconds", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_rules",
                        to="accounts.customer",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_rules",
                        to="inventory.environment",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_rules",
                        to="inventory.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_hints", models.JSONField(default=list)),
                ("actions", models.JSONField(default=list)),
                ("rationale", models.TextField()),
                ("destructive", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_recommendation",
                        to="monitoring.alert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_true_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_states",
                        to="inventory.machine",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="monitoring.monitoringrule",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["customer", "status", "severity"],
                name="monitoring__custome_d9ba01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["machine", "dedup_key", "status"],
                name="monitoring__machine_295c06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["customer", "detected_at"],
                name="monitoring__custome_de4322_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["machine", "detected_at"], name="monitoring__machine_65e65c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringrule",
            index=models.Index(
                fields=["customer", "metric", "enabled"],
                name="monitoring__custome_456c12_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulestate",
            constraint=models.UniqueConstraint(
                fields=("rule", "machine"), name="uniq_rule_machine_state"
            ),
        ),
    ]
