# Generated by Django 6.0.6 on 2026-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RESOLVED'), _negated=True), fields=('customer', 'dedup_key'), name='uniq_open_alert_customer_dedup'),
        ),
    ]
