# Generated by Django 6.0.6 on 2026-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("metrics", "0001_initial"),
        ("monitoring", "0003_remove_rulestate_uniq_rule_machine_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomaly",
            name="window_start",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="anomaly",
            constraint=models.UniqueConstraint(
                condition=models.Q(("window_start__isnull", False)),
                fields=("customer", "machine", "model_version", "window_start"),
                name="uniq_anomaly_model_machine_window",
            ),
        ),
    ]
